---
title: "Genetics and PIT Tags" 
subtitle: "Evaluating Hatchery Impacts on Natural-Origin Steelhead in the Upper Columbia With Multiple Technologies"
author:
  - name: Kevin See
    affliation-ref: wdfw
    corresponding: true
    email: Kevin.See@dfw.wa.gov
affliations:
  - id: wdfw
    name: Washington Department of Fish & Wildlife
    city: Olympia
    state: WA
date: "April 7, 2026"
format: 
  revealjs:
    theme: dark
  # pptx: 
  #   reference-doc: "C:/Users/seek1477/OneDrive - Washington State Executive Branch Agencies/Documents/Custom Office Templates/WDFW_PowerPointTemplate_wide_format_2024.potx"
editor: visual
collapse: TRUE
warning: FALSE
message: FALSE
echo: FALSE
comment: "#>"
fig.path: "figures/"
dpi: 300
---

```{r packages}
# load these packages
library(tidyverse)
library(here)
library(STADEM)
library(DABOM)
library(lubridate)
library(janitor)
# library(msm)
library(sroem)
library(readxl)
library(english)
library(colorspace)
library(flextable)

theme_set(theme_bw())

# flextable default settings
set_flextable_defaults(theme_fun = theme_vanilla,
                       big.mark = ",",
                       na_str = "-",
                       nan_str = "-",
                       # font.family = "Times",
                       font.size = 10,
                       float = "float")


```

```{r genetic-data}
# set year
yr = 2025

# all detections
load(here('analysis/data/derived_data/PITcleanr',
            paste0('UC_Steelhead_', yr, '.rda')))

# read in full genetic summary data
gen_df <-
    read_excel("T:/DFW-Team FP Upper Columbia Escapement - General/UC_Sthd/inputs/Bio Data/Sex and Origin PRD-Brood Comparison Data/Genetics_PBT_GSI/AppendixI_OmyPRD2024(Jul01-Oct31).xlsx",
             sheet = "PBT_GSI",
             skip = 1) |>
  clean_names() |>
  rename(probability_gsi_1 = probability_19,
         gsi_assignment_2 = x2nd_best_estimate,
         probability_gsi_2 = probability_22,
         gsi_assignment_3 = x3rd_best_estimate,
         probability_gsi_3 = probability_24,
         byrne_statwk = byrn_estatwk,
         pit_tag = pit_tag_number,
         gen_rear = rear) |>
  # drop any row with no PIT tag number
  filter(!is.na(pit_tag)) |>
  # flip any PIT tag that's marked as the "secondary" PIT tag in the bio data
  left_join(bio_df |>
              select(primary_pit_tag = pit_tag,
                     second_pit_tag),
            by = join_by(pit_tag == second_pit_tag)) |>
  mutate(across(pit_tag,
                ~ case_when(is.na(primary_pit_tag) ~ .,
                             !is.na(primary_pit_tag) ~ primary_pit_tag,
                            .default = .))) |>
  select(-primary_pit_tag)

```

```{r load-data}
# tag summary
tag_summ <-
  query_dabom_results(query_year = yr,
                      result_type = "tag_summ") |>
    left_join(gen_df |> 
              select(tag_code = pit_tag,
                     hatchery_byname,
                     by),
            by = join_by(tag_code)) |> 
  mutate(across(origin,
                ~ case_match(.,
                             "W" ~ "NOR",
                             "H" ~ "HOR",
                             .default = .))) |> 
  mutate(ovrst = case_when(str_detect(gsi_assignment,
                                      "UPPCOL") &
                             origin == "NOR" ~ F,
                           str_detect(gsi_assignment,
                                      "UPPCOL",
                                      negate = T) &
                             origin == "NOR" ~ T,
                           origin == "HOR" &
                             hatchery_byname %in% c("OmyEAST",
                                                    "OmyWELL",
                                                    "OmyWMET",
                                                    "OmyWOKA",
                                                    "OmyWOMA",
                                                    "OmyWINT") ~ F,
                           origin == "HOR" &
                             !hatchery_byname %in% c("OmyEAST",
                                                     "OmyWELL",
                                                     "OmyWMET",
                                                     "OmyWOKA",
                                                     "OmyWOMA",
                                                     "OmyWINT") ~ T,
                           .default = NA)) |> 
  mutate(uc_hatch_grp = case_when(origin == "H" &
                                    !ovrst &
                                    hatchery_byname == "OmyEAST" ~ "Wenatchee",
                                  origin == "H" &
                                    !ovrst &
                                    hatchery_byname == "OmyWINT" ~ "Methow",
                                  origin == "H" &
                                    !ovrst &
                                    hatchery_byname == c("OmyWELL") ~ "Wells",
                                  origin == "H" &
                                    !ovrst &
                                    hatchery_byname %in% c("OmyWMET",
                                                           "OmyWOKA",
                                                           "OmyWOMA") ~ "Other",
                                  .default = NA_character_))

tag_summ <-
  tag_summ |> 
  filter(!is.na(ovrst))

# tag_summ |>
#   tabyl(origin, ovrst) |>
#   adorn_totals(where = c("row", "col")) |> 
#   adorn_percentages() |>
#   adorn_pct_formatting()
```

```{r tag-rate}
tag_rate <-
  query_dabom_results(dabom_dam_nm = "RockIsland",
                      query_year = yr,
                      result_type = "dam_summ") |> 
  filter(dam == "RockIsland") |> 
  select(year, 
         dam,
         origin,
         priest_cnt,
         priest_cnt_se) |> 
  mutate(across(origin,
                ~ case_match(.,
                             "W" ~ "NOR",
                             "H" ~ "HOR",
                             .default = .))) |> 
  left_join(tag_summ |> 
              count(origin,
                    name = "n_tags"),
            by = join_by(origin)) |> 
  mutate(tag_rate = n_tags / priest_cnt,
         tag_rate_se = n_tags / priest_cnt^2 * priest_cnt_se)

```

```{r}
all_dets <-
  tag_summ |> 
  select(tag_code,
         origin,
         ovrst,
         group) |> 
  left_join(prepped_ch, 
            by = join_by(tag_code))

# furtherst upstream dam reached by overshoot fish
ovrst_tags <-
  all_dets |> 
  filter(ovrst) |> 
  group_by(tag_code,
           origin) |> 
  summarize(det_PRA = if_else(sum(str_detect(path, "PRA")) > 0, T, F),
            det_RIA = if_else(sum(str_detect(path, "RIA")) > 0, T, F),
            det_RRF = if_else(sum(str_detect(path, "RRF")) > 0, T, F),
            det_WEA = if_else(sum(str_detect(path, "WEA")) > 0, T, F),
            n_dams = det_PRA + det_RIA + det_RRF + det_WEA,
            .groups = "drop") |>
  mutate(ovrst_dam = case_when(det_PRA & !det_RIA ~ "Priest Rapids",
                                det_RIA & !det_RRF ~ "Rock Island",
                                det_RRF & !det_WEA ~ "Rocky Reach",
                                det_WEA ~ "Wells"),
         across(ovrst_dam,
                ~ fct_reorder(.,
                              n_dams))) |> 
  select(-starts_with("det_")) |> 
  left_join(tag_summ |> 
              select(tag_code,
                     final_node,
                     node_group = group),
            by = join_by(tag_code))

ovrst_dams <-
  tibble(dam_code = as_factor(c("PRA",
                                "RIA",
                                "RRF",
                                "WEA")),
         dam = case_match(dam_code,
                          "PRA" ~ "Priest Rapids",
                          "RIA" ~ "Rock Island",
                          "RRF" ~ "Rocky Reach",
                          "WEA" ~ "Wells",
                          .default = NA_character_)) |>
  mutate(across(dam,
                ~ factor(., levels = levels(ovrst_tags$ovrst_dam)))) |> 
  mutate(tag_cnts = map(dam_code,
                        .f = function(dam_code) {
                          all_dets |> 
                            group_by(origin,
                                    ovrst) |> 
                           summarize(n_tags = n_distinct(tag_code[str_detect(path, as.character(dam_code))]),
                                     .groups = "drop")
                       })) |> 
  unnest(tag_cnts) |> 
  left_join(tag_rate |> 
              select(origin,
                     contains("tag_rate")),
            by = join_by(origin)) |> 
  mutate(abund = n_tags / tag_rate,
         abund_se = n_tags * tag_rate_se / tag_rate^2)

ovrst_last_dam <-
  ovrst_tags |> 
  group_by(origin, ovrst_dam) |> 
  summarize(n_tags = n_distinct(tag_code), 
            .groups = "drop") |> 
  left_join(tag_rate |> 
              select(origin,
                     contains("tag_rate")),
            by = join_by(origin)) |> 
  mutate(abund = n_tags / tag_rate,
           abund_se = n_tags * tag_rate_se / tag_rate^2)

```

```{r}
flbk_prop <-
  ovrst_tags |> 
  count(ovrst_dam,
        origin,
        node_group,
        name = "n_tags") |> 
  group_by(ovrst_dam,
           origin) |> 
  mutate(tot_tags = sum(n_tags),
         prop = n_tags / tot_tags,
         prop_se = sqrt((prop * (1 - prop)) / tot_tags),
         prop_lci = qnorm(0.025, prop, prop_se),
         prop_uci = qnorm(0.975, prop, prop_se),
         across(c(prop_lci,
                  prop_uci),
                ~ case_when(. < 0 ~ 0,
                            . > 1 ~ 1,
                            .default = .))) |> 
  ungroup() |> 
  filter(node_group == "BelowPriest")
```

```{r methow-hatch-prep}
wells_rrf <-
  tag_summ |> 
  filter(hatchery_byname %in% c(#"OmyEAST",
                                "OmyWELL",
                                "OmyWMET",
                                "OmyWOKA",
                                "OmyWOMA",
                                "OmyWINT")) |> 
  select(tag_code,
         hatchery_byname,
         origin) |> 
  left_join(prepped_ch,
            by = join_by(tag_code)) |> 
  filter(str_detect(path, "RRF")) |> 
  select(tag_code,
         hatchery_byname) |> 
  distinct() |> 
  left_join(tag_summ,
            by = join_by(tag_code,
                         hatchery_byname)) |> 
  mutate(final_det = case_when(final_node == "FST" ~ "Foster Creek",
                               final_node == "RRF" ~ "Rocky Reach Dam",
                               str_detect(final_node, "WEH") ~ "Wells Hatchery",
                               str_detect(final_node, "EBO") ~ "East Bank Hatchery",
                               .default = group),
         across(final_det,
                ~ case_match(.,
                             "WellsPool" ~ "Wells Pool",
                             .default = .)))

```


```{r east-bank-prep}
eb_ria <-
  tag_summ |> 
  filter(hatchery_byname == "OmyEAST") |> 
  select(tag_code,
         origin) |> 
  left_join(prepped_ch,
            by = join_by(tag_code)) |> 
  filter(str_detect(path, "RIA")) |> 
  select(tag_code) |> 
  distinct() |> 
  left_join(tag_summ,
            by = join_by(tag_code)) |> 
  mutate(final_det = case_when(final_node == "FST" ~ "Foster Creek",
                               final_node == "RRF" ~ "Rocky Reach Dam",
                               final_node == "RIA" ~ "Rock Island Dam",
                               str_detect(final_node, "WEH") ~ "Wells Hatchery",
                               str_detect(final_node, "EBO") ~ "East Bank Hatchery",
                               .default = group),
         across(final_det,
                ~ case_match(.,
                             "WellsPool" ~ "Wells Pool",
                             .default = .)))
```
